name: Publish New Tag
run-name: Pushing git tag ${{ inputs.tag_name }} by @${{ github.actor }}

on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: "The name of the new tag (e.g., v1.0.0)"
                required: true
            tag_message:
                description: "A message for the tag (optional)"
                required: false

jobs:
    publish_tag:
        runs-on: ubuntu-latest

        steps:
            - name: Verify version string format
              run: |
                  if [[ ! "${{ github.event.inputs.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                      echo "Error: Version string must follow the format 'vMAJOR.MINOR.PATCH' (e.g., v1.0.0)."
                      exit 1
                  fi

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Create and push tag
              run: |
                  TAG_NAME="${{ github.event.inputs.tag_name }}"
                  TAG_MESSAGE="${{ github.event.inputs.tag_message }}"

                  if [ -z "$TAG_MESSAGE" ]; then
                    git tag "$TAG_NAME"
                  else
                    git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
                  fi

                  git push origin "$TAG_NAME"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
