name: Publish Git Tag
run-name: Publishing git tag ${{ inputs.tag_name }} by @${{ github.actor }}

on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: "The name of the new tag (e.g., v1.0.0)"
                required: true
            tag_message:
                description: "A message for the tag (optional)"
                required: false

jobs:
    publish_git:
        runs-on: ubuntu-latest

        steps:
            - uses: matt-usurp/validate-semver@v2
              id: semver
              with:
                  version: ${{ github.event.inputs.tag_name }}

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Create and push tag
              run: |
                  TAG_NAME="${{ steps.semver.outputs.version }}"
                  TAG_MESSAGE="${{ github.event.inputs.tag_message }}"

                  git config --global user.name 'Github Actions'
                  git config --global user.email '64446617+ZackarySantana@users.noreply.github.com'

                  if [ -z "$TAG_MESSAGE" ]; then
                    git tag "v$TAG_NAME"
                  else
                    git tag -a "v$TAG_NAME" -m "$TAG_MESSAGE"
                  fi

                  git push origin "v$TAG_NAME"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
