name: Publish Docker Image
run-name: Publishing docker tag ${{ inputs.image_tag }} by @${{ github.actor }}

on:
    workflow_dispatch:
        inputs:
            image_tag:
                description: "The tag for the Docker image (e.g., v1.0.0)"
                required: true

defaults:
    run:
        working-directory: goskip-image

jobs:
    build_and_publish:
        runs-on: ubuntu-latest

        steps:
            - uses: matt-usurp/validate-semver@v2
              id: semver
              with:
                  version: ${{ github.event.inputs.image_tag }}

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and tag Docker image
              run: |
                  docker build -t lidtop/goskip:latest .
                  docker tag lidtop/goskip:latest lidtop/goskip:v${{ steps.semver.outputs.version }}

            - name: Push Docker image
              run: |
                  docker push lidtop/goskip:v${{ steps.semver.outputs.version }}
                  docker push lidtop/goskip:latest
